name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Set up dart
        uses: dart-lang/setup-dart@v1
      
      - name: Get dependencies
        run: dart pub get --no-example
      
      - name: Static code analysis
        run: dart analyze --fatal-infos
      
      - name: Check code formatting
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Unit tests
        run: dart test --test-randomize-ordering-seed=random
    
      - name: Set up commands
        uses: Nikoro/setup-commands@v1
        with:
          ref: ${{ github.sha }}

      - name: Activate commands
        working-directory: example
        run: commands

      - name: Integration tests
        working-directory: example
        run: dart test --concurrency=1
